// On The Case HTML helpers. Identity comes from source-native URL shapes.
export type HtmlAnchor = { href: string; text: string };
const ENTITY_MAP: Record<string,string> = { amp:'&', apos:"'", quot:'"', lt:'<', gt:'>', nbsp:' ', pound:'£', ndash:'–', mdash:'—' };
export function decodeHtml(value:string):string { return value.replace(/&#(\d+);/g,(_a,c)=>String.fromCodePoint(Number(c))).replace(/&#x([0-9a-f]+);/gi,(_a,c)=>String.fromCodePoint(Number.parseInt(c,16))).replace(/&([a-z]+);/gi,(a,n)=>ENTITY_MAP[n.toLowerCase()]??a); }
export function textFromHtml(html:string):string { return decodeHtml(html).replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<(?:br|p|div|li|tr|h[1-6])\b[^>]*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[\t\r ]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim(); }
export function titleFromHtml(html:string):string|undefined { const m=html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i); return m?textFromHtml(m[1]).trim():undefined; }
export function isOnTheCaseHost(hostname:string):boolean { return hostname==='onthecasemusic.co.uk'||hostname==='www.onthecasemusic.co.uk'; }
export function anchorsFromHtml(html:string,baseUrl:string):HtmlAnchor[]{ const out:HtmlAnchor[]=[]; for(const m of html.matchAll(/<a\b[^>]*?href\s*=\s*(["'])(.*?)\1[^>]*>([\s\S]*?)<\/a>/gi)){ try{const u=new URL(decodeHtml(m[2]),baseUrl);if(!isOnTheCaseHost(u.hostname))continue;u.hash='';out.push({href:u.toString(),text:textFromHtml(m[3]).trim()});}catch{}} return out; }
export function uniqueBy<T>(items:T[],key:(item:T)=>string):T[]{const seen=new Set<string>();return items.filter(i=>{const k=key(i);if(seen.has(k))return false;seen.add(k);return true;});}
export function bandRef(urlText:string){try{const m=new URL(urlText).pathname.match(/^\/bands\/(\d+)\/([^/]+)$/);return m?{id:m[1],slug:m[2]}:undefined;}catch{return undefined;}}
export function venueRef(urlText:string){try{const m=new URL(urlText).pathname.match(/^\/venues\/(\d+)\/([^/]+)$/);return m?{id:m[1],slug:m[2]}:undefined;}catch{return undefined;}}
export function gigRef(urlText:string){try{const m=new URL(urlText).pathname.match(/^\/venues\/(\d+)\/([^/]+)\/(\d+)$/);return m?{venueId:m[1],venueSlug:m[2],gigId:m[3]}:undefined;}catch{return undefined;}}
const MONTHS:Record<string,number>={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
export function parseLongDate(text:string){const m=text.replace(/\s+/g,' ').trim().match(/(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})/);if(!m)return;const mo=MONTHS[m[2].toLowerCase()];const d=Number(m[1]);if(!mo||d<1||d>31)return;return `${m[3]}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
export function parseClockTime(text:string){const c=text.replace(/\s+/g,' ').trim().toUpperCase();const m=c.match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/);if(m){let h=Number(m[1]);if(h<1||h>12)return; if(m[3]==='PM'&&h<12)h+=12;if(m[3]==='AM'&&h===12)h=0;return `${String(h).padStart(2,'0')}:${m[2]??'00'}`;}const n=c.match(/^(\d{1,2}):(\d{2})$/);return n&&Number(n[1])<=23?`${String(Number(n[1])).padStart(2,'0')}:${n[2]}`:undefined;}
export function parseTimePrice(text:string):{startTime?:string;admissionStatus?:string;price?:string}{const p=text.replace(/\s+/g,' ').trim().split('/').map(x=>x.trim()).filter(Boolean);const o:any={};if(p[0])o.startTime=parseClockTime(p[0]);if(/^free$/i.test(p[1]??''))o.admissionStatus='FREE_CONFIRMED';else if(/£\s*\d/.test(p[1]??'')){o.admissionStatus='PAID_CONFIRMED';o.price=p[1];}return o;}
export function splitActAtVenue(title:string){const c=title.replace(/\s+/g,' ').trim();const i=c.toLowerCase().indexOf(' at ');return i===-1?{actName:c}:{actName:c.slice(0,i).trim(),venueName:c.slice(i+4).trim()};}
