import type { GigSource } from '../../../knowledge/types.js';
import type { AcquisitionRouter } from '../../runner/acquisition.js';
import { registerSourceAdapter, type SourceAdapter } from '../../runner/adapter.js';
import type { FetchedSource, ParsedSource, SourceRunContext } from '../../runner/types.js';
import { isOnTheCaseHost } from './html.js';
import { parseOnTheCase } from './parse.js';
export const ONTHECASE_ADAPTER_ID='onthecase';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function fetchWithRetry(url:string,acquisition:AcquisitionRouter):Promise<FetchedSource>{let lastError:unknown;await sleep(300+Math.floor(Math.random()*500));for(let attempt=0;attempt<8;attempt++){try{return await acquisition.acquire({url,kind:'html',timeoutMs:25000,maxBytes:4*1024*1024,complete:false,fetchMethod:'http-onthecase',followRedirects:true,maxRedirects:5,headers:{accept:'text/html,application/xhtml+xml','user-agent':'BNDY-Backline/1.0 (+https://bndy.live; source-reconciliation)'}});}catch(error){lastError=error;const message=error instanceof Error?error.message:String(error);const retryable=/HTTP (403|408|425|429|5\d\d)|fetch failed|timed? ?out|abort/i.test(message);if(attempt===7||!retryable)throw error;await sleep(Math.min(12000,750*(2**attempt))+Math.floor(Math.random()*1000));}}throw lastError;}
export const onTheCaseAdapter:SourceAdapter={async fetch(config:GigSource,run:SourceRunContext,acquisition:AcquisitionRouter){if(config.runtimeClass!=='standard')throw new Error('On The Case must use the standard HTTP runtime');const taskUrl=typeof run.task?.url==='string'?run.task.url:undefined;const url=taskUrl??config.url;if(!url)throw new Error(`On The Case source ${config.id} requires a URL`);const parsed=new URL(url);if(!isOnTheCaseHost(parsed.hostname))throw new Error(`On The Case adapter refused non-On The Case URL: ${parsed.hostname}`);return fetchWithRetry(parsed.toString(),acquisition);},async parse(_config:GigSource,run:SourceRunContext,raw:FetchedSource):Promise<ParsedSource>{const sourceUrl=raw.sourceUrl;if(!sourceUrl)throw new Error('On The Case acquisition returned no source URL');if(!/<(?:html|body|head|a)\b/i.test(raw.body))throw new Error('On The Case structural gate failed: response is not recognisable HTML');return parseOnTheCase(raw.body,sourceUrl,run);}};
registerSourceAdapter(ONTHECASE_ADAPTER_ID,onTheCaseAdapter);
