import { createHash } from 'node:crypto';
import type { NormalisedSourceClaim,NormalisedSourceEntity,NormalisedSourceEvent,ParsedSource,SourceFanoutRequest,SourceRunContext } from '../../runner/types.js';
import { anchorsFromHtml,bandRef,gigRef,parseLongDate,parseTimePrice,splitActAtVenue,textFromHtml,titleFromHtml,uniqueBy,venueRef } from './html.js';
const HOME='On The Case Music Services';
const EXPECTED:Record<string,RegExp>={'gig-index':/^Gigs\s*:/i,'band-index':/^Bands\s*:/i,'venue-index':/^Venues/i,band:/^Bands\s*:/i,venue:/^Venues/i,'full-reconcile':/^Gigs\s*:|^On The Case/i};
function kind(run:SourceRunContext){const k=run.task?.kind;if(typeof k==='string')return k;if(run.sourceId.includes('band-index'))return'band-index';if(run.sourceId.includes('venue-index'))return'venue-index';if(run.sourceId.includes('band-hydration'))return'band';if(run.sourceId.includes('venue-hydration'))return'venue';if(run.sourceId.includes('full-reconcile'))return'full-reconcile';return'gig-index';}
function req(sourceId:string,k:string,url:string,nativeId?:string,name?:string,extra?:Record<string,unknown>):SourceFanoutRequest{return{sourceId,taskKey:`${k}:${nativeId??url}`,task:{kind:k,url,...(nativeId?{nativeId}:{}),...(name?{name}:{}),...extra}};}
function gate(k:string,html:string){const t=titleFromHtml(html)??'';if(t.includes(HOME))throw new Error(`On The Case structural gate failed: server returned the homepage for a ${k} task`);if(EXPECTED[k]&&!EXPECTED[k].test(t))throw new Error(`On The Case structural gate failed: unexpected title "${t}" for a ${k} task`);}
function venueTask(id:string,slug:string,name?:string){return req('onthecase-venue-hydration','venue',`https://onthecasemusic.co.uk/venues/${id}/${slug}`,`onthecase:venue:${id}`,name);}
function bandTask(id:string,slug:string,name?:string){return req('onthecase-band-hydration','band',`https://onthecasemusic.co.uk/bands/${id}/${slug}`,`onthecase:band:${id}`,name);}
function nonArtist(v:string){return /\b(open\s*mic|buskers?(?:\s+night)?|jam\s+night|open\s+stage|music\s+club)\b/i.test(v.trim());}
function splitAddressPhone(text:string){const p=text.replace(/\s+/g,' ').trim().split('/').map(x=>x.trim()).filter(Boolean);const last=p.at(-1)??'';return /^0\d[\d ]{7,}$/.test(last)?{address:p.slice(0,-1).join(', ')||undefined,phone:last}:{address:p.join(', ')||undefined};}
function gigIndex(html:string,url:string):ParsedSource{const events:NormalisedSourceEvent[]=[];const warnings:string[]=[];for(const block of html.split(/<div class="list-item">/i).slice(1)){const dm=block.match(/<div class="list-item-left">([\s\S]*?)<\/div>/i);const date=dm?parseLongDate(textFromHtml(dm[1])):undefined;for(const row of block.matchAll(/<div class="name">\s*<a href="([^"]+)">([\s\S]*?)<\/a>(?:\s*<br\s*\/?>\s*<span>([\s\S]*?)<\/span>)?[\s\S]*?<div class="price">([\s\S]*?)<\/div>/gi)){const g=gigRef(new URL(row[1],url).toString());if(!g){warnings.push(`gig row link did not carry a gig ID: ${row[1]}`);continue;}const title=textFromHtml(row[2]);const {actName,venueName}=splitActAtVenue(title);const {address,phone}=splitAddressPhone(row[3]?textFromHtml(row[3]):'');const {startTime,admissionStatus,price}=parseTimePrice((textFromHtml(row[4]).split('\n')[0]??''));const claims:NormalisedSourceClaim[]=phone?[{predicate:'derivedFrom',value:{kind:'venue-phone',venue:`onthecase:venue:${g.venueId}`,phone}}]:[];const e:NormalisedSourceEvent={sourceEventKey:`onthecase:gig:${g.gigId}`,sourceNativeId:g.gigId,artistName:actName&&!nonArtist(actName)?actName:undefined,venueName,venueExternalId:`onthecase:venue:${g.venueId}`,venueAddress:address,date,startTime,title,eventUrl:`https://onthecasemusic.co.uk/venues/${g.venueId}/${g.venueSlug}/${g.gigId}`,admissionStatus,price,claims:claims.length?claims:undefined,data:{venueSlug:g.venueSlug,unresolvedPerformerLabel:nonArtist(actName)?actName:undefined}};e.contentHash=createHash('sha256').update(JSON.stringify({key:e.sourceEventKey,date,startTime,title,admissionStatus,price,address})).digest('hex');events.push(e);}}
const dedup=uniqueBy(events,e=>e.sourceEventKey);if(!new URL(url).search&&!dedup.length)throw new Error('On The Case structural gate failed: root gig listing parsed to zero gigs');const next=uniqueBy(dedup.map(e=>{const slug=String((e.data as any)?.venueSlug??'');return venueTask(e.venueExternalId!.split(':')[2],slug,e.venueName);}),x=>x.taskKey);if(!new URL(url).search)next.push(req('onthecase-gig-index','gig-inventory-control',url,'onthecase:gig-inventory:root',undefined,{expectedCount:dedup.length,inventoryLevel:'gig-index-root',inventoryCountSource:'parsed-gig-links'}));return{events:dedup,nextRequests:next,parked:[],warnings};}
function bandIndex(html:string,url:string):ParsedSource{const tasks=uniqueBy(anchorsFromHtml(html,url).map(a=>({a,r:bandRef(a.href)})).filter(x=>x.r).map(x=>bandTask(x.r!.id,x.r!.slug,x.a.text||undefined)),x=>x.taskKey);return{events:[],nextRequests:[...tasks,req('onthecase-band-index','band-inventory-control',url,'onthecase:band-inventory:root',undefined,{expectedCount:tasks.length,inventoryLevel:'band-directory',inventoryCountSource:'parsed-profile-links'})],parked:[],warnings:[]};}
function venueIndex(html:string,url:string):ParsedSource{const tasks=uniqueBy(anchorsFromHtml(html,url).map(a=>({a,r:venueRef(a.href)})).filter(x=>x.r).map(x=>venueTask(x.r!.id,x.r!.slug,x.a.text||undefined)),x=>x.taskKey);const root=!new URL(url).search;const locations=root?uniqueBy(anchorsFromHtml(html,url).filter(a=>/\/venues\?location=/.test(a.href)).map(a=>req('onthecase-venue-index','venue-index',a.href,`onthecase:venue-location:${new URL(a.href).searchParams.get('location')??a.href}`,a.text)),x=>x.taskKey):[];return{events:[],nextRequests:[...tasks,...locations,req('onthecase-venue-index','venue-inventory-control',url,`onthecase:venue-inventory:${new URL(url).searchParams.get('location')??'default'}`,undefined,{expectedCount:tasks.length,inventoryLevel:'venue-directory-page',inventoryCountSource:'parsed-profile-links'})],parked:[],warnings:[]};}
function profile(html:string,url:string,type:'band'|'venue'):ParsedSource{const ref=type==='band'?bandRef(url):venueRef(url);if(!ref)throw new Error(`On The Case ${type} task URL is not a profile: ${url}`);const h=html.match(/<div class="gigs-item">\s*<h2>([\s\S]*?)<\/h2>/i);const lines=h?textFromHtml(h[1]).split('\n').map(x=>x.trim()).filter(Boolean):[];const name=lines[0];const claims:NormalisedSourceClaim[]=[];if(name)claims.push({predicate:'hasName',value:name});if(type==='band'){for(const genre of (lines[1]??'').split('/').map(x=>x.trim()).filter(Boolean))claims.push({predicate:'hasGenre',value:genre,evidenceText:lines[1]});}else{const {address,phone}=splitAddressPhone(lines[1]??'');if(address)claims.push({predicate:'hasAddress',value:address,evidenceText:lines[1]});if(phone)claims.push({predicate:'derivedFrom',value:{kind:'venue-phone',phone}});}
const entity:NormalisedSourceEntity={entityType:type==='band'?'artist':'venue',sourceEntityKey:`onthecase:${type}:${ref.id}`,sourceNativeId:ref.id,displayName:name,sourceUrl:url,claims};if(type==='band')return{events:[],entities:[entity],nextRequests:[],parked:[],warnings:name?[]:[`band ${ref.id} profile had no parseable name heading`]};const bandTasks=uniqueBy(anchorsFromHtml(html,url).map(a=>({a,r:bandRef(a.href)})).filter(x=>x.r).map(x=>bandTask(x.r!.id,x.r!.slug,x.a.text||undefined)),x=>x.taskKey);return{events:[],entities:[entity],nextRequests:bandTasks,parked:[],warnings:name?[]:[`venue ${ref.id} profile had no parseable name heading`]};}
export function parseOnTheCase(html:string,url:string,run:SourceRunContext):ParsedSource{const k=kind(run);if(k.endsWith('-inventory-control'))return{events:[],parked:[],warnings:[]};gate(k,html);if(k==='full-reconcile')return{events:[],nextRequests:[req('onthecase-gig-index','gig-index','https://onthecasemusic.co.uk/gigs')],parked:[],warnings:[]};if(k==='gig-index')return gigIndex(html,url);if(k==='band-index')return bandIndex(html,url);if(k==='venue-index')return venueIndex(html,url);if(k==='band')return profile(html,url,'band');if(k==='venue')return profile(html,url,'venue');throw new Error(`Unsupported On The Case task kind: ${k}`);}
