import type { GigSource } from '../../../knowledge/types.js';
const common: Pick<GigSource,'type'|'timezone'|'cadence'|'localTime'|'region'|'authorityClass'|'thresholds'|'adapter'|'runtimeClass'|'enabled'|'shadow'|'writerAuthority'|'health'>={type:'CURATED_SOURCE',timezone:'Europe/London',cadence:'manual',localTime:'02:40',region:'North East England',authorityClass:'curated',thresholds:{artistAutoMatch:0.98,venueAutoMatch:0.98,eventAutoCreate:0.995,socialAutoAttach:0.995},adapter:'onthecase',runtimeClass:'standard',enabled:false,shadow:true,writerAuthority:'cowork',health:'unknown'};
export const ONTHECASE_SOURCES:GigSource[]=[
{...common,id:'onthecase-gig-index',name:'On The Case future gig listing',url:'https://onthecasemusic.co.uk/gigs',mode:'delta',snapshotSemantics:'complete',enabled:true,sourceFamily:'onthecase',sourceRole:'coverage-root',scheduleAuthority:'eventbridge',effectiveCadence:'hourly',maxStalenessHours:26,
  // Pilot-safe by construction (ADR-113). Live writes still need shadow=false,
  // writerAuthority=aws, the global control and pilotCandidateKeys in the registry.
  projectionPolicy:{mode:'additive-only',allowedActions:['create'],entityCreation:'match-only',maxProjectionActionsPerRun:400,
    allowedPredicates:['hasPerformerName','hasPerformer','hasVenueName','occursAt','occursOn','startsAt','endsAt','hasTitle','hasEventUrl','hasTicketUrl','hasAdmissionStatus','hasPrice','hasStatus','derivedFrom','hasGenre']}},
{...common,id:'onthecase-band-index',name:'On The Case band directory (manual bootstrap/audit only)',url:'https://onthecasemusic.co.uk/bands',mode:'append-only',snapshotSemantics:'complete',sourceFamily:'onthecase',sourceRole:'maintenance',scheduleAuthority:'manual',effectiveCadence:'manual'},
{...common,id:'onthecase-venue-index',name:'On The Case venue directory (manual bootstrap/audit only)',url:'https://onthecasemusic.co.uk/venues',mode:'append-only',snapshotSemantics:'incremental',sourceFamily:'onthecase',sourceRole:'maintenance',scheduleAuthority:'manual',effectiveCadence:'manual'},
{...common,id:'onthecase-band-hydration',name:'On The Case band profiles',mode:'append-only',snapshotSemantics:'one_shot',sourceFamily:'onthecase',sourceRole:'child',scheduleAuthority:'child',effectiveCadence:'on-discovery'},
{...common,id:'onthecase-venue-hydration',name:'On The Case venue profiles',mode:'append-only',snapshotSemantics:'one_shot',sourceFamily:'onthecase',sourceRole:'child',scheduleAuthority:'child',effectiveCadence:'on-discovery'},
{...common,id:'onthecase-full-reconcile',name:'On The Case gig-led reconciliation',url:'https://onthecasemusic.co.uk/gigs',mode:'append-only',snapshotSemantics:'incremental',sourceFamily:'onthecase',sourceRole:'maintenance',scheduleAuthority:'manual',effectiveCadence:'manual'}];
