const ENTITY_MAP: Record<string, string> = { amp: '&', apos: "'", quot: '"', lt: '<', gt: '>', nbsp: ' ', pound: '£', ndash: '–', mdash: '—' };
export function decodeHtml(value: string): string { return value.replace(/&#(\d+);/g, (_a, c) => String.fromCodePoint(Number(c))).replace(/&#x([0-9a-f]+);/gi, (_a, c) => String.fromCodePoint(Number.parseInt(c, 16))).replace(/&([a-z]+);/gi, (a, n) => ENTITY_MAP[n.toLowerCase()] ?? a); }
export function textFromHtml(html: string): string { return decodeHtml(html).replace(/<script\b[\s\S]*?<\/script>/gi, ' ').replace(/<style\b[\s\S]*?<\/style>/gi, ' ').replace(/<(?:br|p|div|li|tr|h[1-6])\b[^>]*>/gi, '\n').replace(/<[^>]+>/g, ' ').replace(/[\t\r ]+/g, ' ').replace(/ *\n */g, '\n').replace(/\n{3,}/g, '\n\n').trim(); }
export function titleFromHtml(html: string): string | undefined { const m = html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i); return m ? textFromHtml(m[1]).trim() : undefined; }
export function isScenicEyeHost(hostname: string): boolean { return hostname === 'scenicmind.co.uk' || hostname === 'www.scenicmind.co.uk'; }
export function slug(value: string): string { return value.toLowerCase().trim().replace(/['’]/g, '').replace(/&/g, 'and').replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, ''); }
const MONTHS: Record<string, number> = { january: 1, february: 2, march: 3, april: 4, may: 5, june: 6, july: 7, august: 8, september: 9, october: 10, november: 11, december: 12 };
export function parseLongDate(text: string): string | undefined { const m = text.replace(/\s+/g, ' ').trim().match(/(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})/); if (!m) return; const month = MONTHS[m[2].toLowerCase()]; const day = Number(m[1]); if (!month || day < 1 || day > 31) return; return `${m[3]}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`; }
export function parseClockTime(text: string): string | undefined { const clean = text.replace(/\s+/g, ' ').trim().toUpperCase(); const m = clean.match(/^(\d{1,2})(?::(\d{2}))?\s*(AM|PM)$/); if (m) { let h = Number(m[1]); if (h < 1 || h > 12) return; if (m[3] === 'PM' && h < 12) h += 12; if (m[3] === 'AM' && h === 12) h = 0; return `${String(h).padStart(2, '0')}:${m[2] ?? '00'}`; } const n = clean.match(/^(\d{1,2}):(\d{2})$/); return n && Number(n[1]) <= 23 ? `${String(Number(n[1])).padStart(2, '0')}:${n[2]}` : undefined; }
export function parseTimeRange(text: string): { startTime?: string; endTime?: string } { const parts = text.replace(/\s+/g, ' ').trim().split(/\s*[-–]\s*/); return { startTime: parts[0] ? parseClockTime(parts[0]) : undefined, endTime: parts[1] ? parseClockTime(parts[1]) : undefined }; }
const UK_POSTCODE = /\b([A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2})\b/i;
export function parseVenueCell(text: string): { venueName?: string; address: string; postcode?: string } { const clean = text.replace(/\s+/g, ' ').trim(); const segments = clean.split(',').map((s) => s.trim()).filter(Boolean); const postcode = clean.match(UK_POSTCODE)?.[1]?.toUpperCase().replace(/\s+/g, ' '); return { venueName: segments[0] || undefined, address: clean, postcode }; }
